#!/usr/bin/env python3
"""Verify the acquisition-engine map against the filesystem and write the inventory.

HOW TO USE
    python operations/internal-gtm/migration/verify_map.py
    python operations/internal-gtm/migration/verify_map.py --write

Classification is judgment and lives in acquisition-engine-map.json. Paths and
file counts are measured here, never typed by hand. Exit code 1 means a mapped
path no longer exists or a real path is claimed by no component.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
GTM_ROOT = HERE.parent
REPO_ROOT = GTM_ROOT.parents[1]
MAP = HERE / "acquisition-engine-map.json"
INVENTORY = HERE / "acquisition-engine-inventory.md"

VALID_FUNCTIONS = {
    "canonical prospect data", "research evidence", "market/ICP logic",
    "trigger discovery", "proof inventory", "qualification", "routing",
    "diagnostic selection", "outreach preparation", "approval packet",
    "automation/scheduling", "reporting", "historical artifact", "duplicate",
    "generated/transient output",
}


def count_files(path: Path) -> int:
    if path.is_file():
        return 1
    if path.is_dir():
        total = 0
        for root, dirs, files in os.walk(path, followlinks=False):
            root_path = Path(root)
            # Windows directory junctions are external runtime dependencies, not
            # acquisition-engine artifacts. Never traverse or count their targets.
            dirs[:] = [
                name for name in dirs
                if not (root_path / name).is_symlink()
                and not (root_path / name).is_junction()
                and name != "__pycache__"
            ]
            total += len(files)
        return total
    return 0


def verify(data: dict) -> tuple[list[str], list[dict]]:
    errors: list[str] = []
    source_root = REPO_ROOT / data["source_root"]
    if not source_root.is_dir():
        return [f"source root missing: {source_root}"], []

    targets = set(data["targets"])
    rows: list[dict] = []
    claimed: set[Path] = set()

    for component in data["components"]:
        if component["function"] not in VALID_FUNCTIONS:
            errors.append(f"{component['id']}: unknown function {component['function']}")
        if component["target"] not in targets:
            errors.append(f"{component['id']}: unknown target {component['target']}")
        total = 0
        for relative in component["paths"]:
            path = source_root / relative
            if not path.exists():
                errors.append(f"{component['id']}: path does not exist: {relative}")
                continue
            claimed.add(path.resolve())
            total += count_files(path)
        rows.append({**component, "files": total})

    top_level = {p.resolve() for p in source_root.iterdir()}
    unclaimed = sorted(
        p for p in top_level
        if not any(str(p).startswith(str(c)) or str(c).startswith(str(p)) for c in claimed)
    )
    for path in unclaimed:
        errors.append(f"unclaimed path: {path.relative_to(source_root)}")

    return errors, rows


def render(data: dict, rows: list[dict]) -> str:
    by_function: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        by_function[row["function"]].append(row)
    by_target: dict[str, int] = defaultdict(int)
    for row in rows:
        by_target[row["target"]] += row["files"]

    total = sum(row["files"] for row in rows)
    lines = [
        "# Acquisition Engine Functional Inventory",
        "",
        f"Compiled {data['compiled_at']}. Source `{data['source_root']}`.",
        "",
        "Generated by `verify_map.py` from `acquisition-engine-map.json`. Counts are measured,",
        "not typed. Re-run before any migration step, because they drift.",
        "",
        f"**Decision:** {data['decision']}",
        "",
        f"Total files across mapped components: {total:,}.",
        "",
        "## By function",
        "",
        "| Function | Components | Files |",
        "|---|---:|---:|",
    ]
    for function in sorted(by_function):
        group = by_function[function]
        lines.append(f"| {function} | {len(group)} | {sum(r['files'] for r in group):,} |")

    lines += ["", "## By target area", "", "| Target | Files | Meaning |", "|---|---:|---|"]
    for target, meaning in data["targets"].items():
        lines.append(f"| `{target}` | {by_target.get(target, 0):,} | {meaning} |")

    lines += ["", "## Components", ""]
    for function in sorted(by_function):
        lines += [f"### {function}", ""]
        for row in sorted(by_function[function], key=lambda r: r["id"]):
            lines += [
                f"**`{row['id']}`** to `{row['target']}` ({row['files']:,} files)",
                "",
                *[f"- `{p}`" for p in row["paths"]],
                "",
                row["note"],
                "",
                f"Provenance: {row['provenance']}",
                "",
            ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    data = json.loads(MAP.read_text(encoding="utf-8"))
    errors, rows = verify(data)
    if args.write and rows:
        INVENTORY.write_text(render(data, rows), encoding="utf-8")
        print(f"written: {INVENTORY}")
    print(f"components: {len(rows)}  files mapped: {sum(r['files'] for r in rows):,}")
    if errors:
        print("\n".join(f"ERROR: {item}" for item in errors), file=sys.stderr)
        return 1
    print("map verified: every path exists and every top-level path is claimed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
