-- Oliviks Kitchen seed data generated from src/data/menu.ts
-- Run after supabase/schema.sql in the Supabase SQL editor.

begin;

delete from public.menu_options;
delete from public.menu_option_groups;
delete from public.menu_items;
delete from public.menu_categories;

insert into public.menu_categories (id, title, blurb, sort_order, is_active) values ('rice', 'Rice', 'Add a protein from Sides to build your plate.', 0, true) on conflict (id) do update set title = excluded.title, blurb = excluded.blurb, sort_order = excluded.sort_order, is_active = excluded.is_active, updated_at = now();
insert into public.menu_categories (id, title, blurb, sort_order, is_active) values ('soups', 'Soups', 'Rich Nigerian soups served with one swallow for scooping.', 1, true) on conflict (id) do update set title = excluded.title, blurb = excluded.blurb, sort_order = excluded.sort_order, is_active = excluded.is_active, updated_at = now();
insert into public.menu_categories (id, title, blurb, sort_order, is_active) values ('sides', 'Sides', 'Fried, grilled, and swallow sides to complete the plate.', 2, true) on conflict (id) do update set title = excluded.title, blurb = excluded.blurb, sort_order = excluded.sort_order, is_active = excluded.is_active, updated_at = now();
insert into public.menu_categories (id, title, blurb, sort_order, is_active) values ('snacks', 'Snacks', 'Sweet, savory, crunchy, and handheld Nigerian snacks.', 3, true) on conflict (id) do update set title = excluded.title, blurb = excluded.blurb, sort_order = excluded.sort_order, is_active = excluded.is_active, updated_at = now();
insert into public.menu_categories (id, title, blurb, sort_order, is_active) values ('drinks', 'Drinks', 'Chilled drinks to go with your meal.', 4, true) on conflict (id) do update set title = excluded.title, blurb = excluded.blurb, sort_order = excluded.sort_order, is_active = excluded.is_active, updated_at = now();

insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('106255e8-4aa3-5996-a465-58c1982dd448'::uuid, 'rice', 'Jollof rice', 'Long-cooked tomato rice with a smoky edge. This is the dish Nigerian parties are built around. A smart first order if you want to understand why. Add a protein from Sides: grilled chicken, turkey, mackerel, or beef.', '2,500 Ft', '/images/dish-jollof.png', array['popular']::text[], true, true, 0) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('f001d69f-608a-5852-9c05-2aee793543b9'::uuid, 'rice', 'Fried rice', 'Basmati rice cooked with turmeric and stir-fried with mixed vegetables. Lighter than jollof, bright and savory. Add a protein from Sides: grilled chicken, turkey, mackerel, or beef.', '2,500 Ft', '/images/dish-fried-rice.png', '{}'::text[], true, false, 1) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('0dade67b-30af-5a6c-a39f-d7bf1b109a2b'::uuid, 'rice', 'Pilau rice', 'Basmati rice cooked in aromatic spices. Warm, fragrant, and filling. A heartier rice plate when you want more depth. Add a protein from Sides: grilled chicken, turkey, mackerel, or beef.', '3,500 Ft', '/images/dish-pilau-rice.png', '{}'::text[], true, false, 2) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('213b1edd-ace2-53ba-a8e0-e04c3992e84d'::uuid, 'soups', 'Egusi soup with one swallow', 'Ground melon seeds cooked with leafy greens into a thick, deeply savory soup. Rich and comforting. Served with one swallow to scoop it up. One of the dishes regulars keep coming back for.', '4,700 Ft', '/images/dish-egusi.jpg', array['popular']::text[], true, true, 0) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('5287e22e-cda4-516b-8998-f798dd01caa2'::uuid, 'soups', 'Oha soup with one swallow', 'A traditional Igbo soup made with oha leaves and a rich, savory base. Earthy and full of flavor. Served with one swallow.', '4,700 Ft', '/images/dish-oha-soup.png', '{}'::text[], true, false, 1) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('315e81a0-170b-5ebb-addb-fa21c296b360'::uuid, 'soups', 'Ogbono soup with one swallow', 'Made from ground ogbono seeds, with a smooth texture and a deep, savory taste. Hearty and comforting. Served with one swallow.', '4,700 Ft', '/images/dish-ogbono.png', '{}'::text[], true, false, 2) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('9854a23f-0234-527a-b352-b2e40b21bd10'::uuid, 'soups', 'Vegetable soup with one swallow', 'A hearty soup loaded with leafy greens and proper seasoning. Comforting and full of flavor. Served with one swallow. Dried fish variant on request, subject to availability.', '4,700 Ft', '/images/dish-vegetable-soup.png', '{}'::text[], true, false, 3) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('b328cd1f-6597-5715-9df4-6f2f1412d83d'::uuid, 'soups', 'Bitter leaf soup with one swallow', 'Bitter leaves cooked in a rich cocoyam base with protein. Earthy and full of flavor, with the gentle bitterness the dish is named for. Served with one swallow.', '4,700 Ft', '/images/dish-soup.jpg', '{}'::text[], true, false, 4) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('4c7f7fdf-c0b4-5c4b-a8c7-23c0a5ef86ac'::uuid, 'soups', 'Okro soup with one swallow', 'A hearty okro soup with protein and proper seasoning. Sticky, savory, and satisfying. Served with one swallow.', '4,700 Ft', '/images/dish-okro-soup.png', '{}'::text[], true, false, 5) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('8e665b25-1ede-592b-a849-f77f010c672f'::uuid, 'soups', 'Groundnut soup with one swallow', 'A rich groundnut-based soup with deep, earthy flavor and protein. Served with one swallow. Contains peanuts.', '4,700 Ft', '/images/dish-groundnut-soup.png', '{}'::text[], true, false, 6) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('277db907-6982-504d-ae63-3e3ea07d4165'::uuid, 'soups', 'Pepper soup', 'A light, aromatic soup with warming spices and gentle pepper. Brothy and comforting. Good when you want something warming.', '5,000 Ft', '/images/dish-pepper-soup.png', '{}'::text[], true, false, 7) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('01e6dc6c-051b-5e2c-8324-06987c64c6bc'::uuid, 'sides', 'Fried Yam', 'Slices of yam fried until crisp outside and soft inside. Simple and satisfying. Good with pepper sauce, fish, or meat.', '2,500 Ft', '/images/dish-fried-yam.png', '{}'::text[], true, false, 0) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('d3f75ce7-7638-5df6-9d4e-89fbaff2c585'::uuid, 'sides', 'Moi Moi', 'Steamed bean pudding made from blended black-eyed peas with peppers and seasoning. Soft and savory. A Nigerian classic.', '1,500 Ft', '/images/dish-moi-moi.png', '{}'::text[], true, false, 1) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('b0af2364-f9c8-543a-8a5b-cb64da6fc731'::uuid, 'sides', 'Fried beef', 'Seasoned beef, fried and full of flavor. Add it to rice or eat it on its own.', '1,500 Ft', '/images/dish-suya-platter.jpg', '{}'::text[], true, false, 2) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('f23ea9cf-722d-5bb1-8b2b-c5938d433637'::uuid, 'sides', 'Fried mackerel (half cut)', 'A half cut of fresh mackerel, seasoned and fried until golden. Good on its own or paired with rice or yam.', '2,000 Ft', '/images/dish-fried-mackerel.png', '{}'::text[], true, false, 3) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('fb7a823b-d0af-59d3-8baf-07457f25e16b'::uuid, 'sides', 'Grilled turkey', 'Seasoned turkey, grilled until juicy. Pairs well with jollof or fried rice.', '1,500 Ft', '/images/dish-grilled-turkey.png', '{}'::text[], true, false, 4) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('c73015b3-9c53-5b47-a79d-0e0f0b41f80f'::uuid, 'sides', 'Grilled Chicken Thigh', 'Chicken thigh, seasoned and grilled until juicy. Pairs well with jollof, fried rice, or plantain.', '1,000 Ft', '/images/dish-grilled-chicken.png', '{}'::text[], true, false, 5) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('680dbb4f-4cf9-5e17-acb7-d1c0f7d93a5d'::uuid, 'sides', 'Suya sticks', 'Grilled beef skewers coated in a bold peanut and pepper spice blend. This is our hottest item, but still easy to enjoy. Smoky and hard to stop eating.', '1,000 Ft', '/images/dish-suya-sticks.jpg', array['popular', 'Our hottest']::text[], true, true, 6) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('0f2ab8aa-c344-504f-b1f7-c50e3c937e89'::uuid, 'sides', 'Poundo Swallow', 'A smooth, soft swallow in the style of pounded yam. The soft side you use to scoop soup. Order it with egusi, oha, or ogbono.', '500 Ft', '/images/dish-poundo.jpg', '{}'::text[], true, false, 7) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('a22d77c0-174d-5f08-8c24-2b7270d9f395'::uuid, 'sides', 'Eba', 'A firm Nigerian swallow made from garri. Pairs perfectly with rich soups like egusi and ogbono.', '500 Ft', '/images/dish-eba.png', '{}'::text[], true, false, 8) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('35989f1b-bdaa-5ec3-8e67-10b3a74e21a6'::uuid, 'snacks', 'Meat Pie', 'A baked pastry filled with seasoned minced meat and vegetables. Satisfying on its own. Easy to love on a first visit.', '1,000 Ft', '/images/dish-meat-pie.png', '{}'::text[], true, false, 0) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('20f3d474-69b1-5671-8cec-e106422d65b2'::uuid, 'snacks', 'Coconut peanut', 'A crunchy peanut and coconut snack. Lightly sweet and easy to share.', '1,500 Ft', '/images/dish-coconut-peanut.png', '{}'::text[], true, false, 1) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('f872c9e6-f554-5a04-8792-efc2cc33925d'::uuid, 'snacks', 'Spicy kuli kuli (one pack)', 'Kuli kuli is a crunchy, spiced peanut snack. Peppery and moreish. Good on its own or alongside a meal.', '2,000 Ft', '/images/dish-kuli-kuli.png', array['Peppery']::text[], true, false, 2) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('2aac7975-a4df-5372-b11f-042251dea6b0'::uuid, 'snacks', 'Fried Plantain', 'Ripe plantain fried until golden and caramelized. Soft and sweet. The easy balance to anything peppery.', '2,500 Ft', '/images/dish-fried-plantain.jpg', array['popular']::text[], true, true, 3) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('963f7cb3-3734-567c-b894-b8e8db923668'::uuid, 'snacks', 'Puff Puff', 'Small fried dough bites, lightly sweet and golden. Easy to love. Good as a first snack, even better after something peppery.', '2,000 Ft', '/images/dish-puff-puff-fresh.jpg', array['popular']::text[], true, true, 4) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('e847b022-b4be-5eb1-9895-23af57341e84'::uuid, 'snacks', 'Plantain chips', 'Thin, crisp plantain chips. Lightly salted and snackable.', '1,000 Ft', '/images/dish-plantain-chips.png', '{}'::text[], true, false, 5) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('f85ce23a-944b-5eaf-97a8-2b420b68bb6f'::uuid, 'snacks', 'Chin Chin', 'Crunchy fried dough made with flour, sugar, milk, and eggs. Lightly sweet and easy to snack on. Good on its own or with a drink.', '1,000 Ft', null, '{}'::text[], true, false, 6) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('494e29cb-5b11-5f54-9896-d0fe45bad8f9'::uuid, 'snacks', 'Fish roll', 'Baked dough rolled around a deboned mackerel filling. Savory and satisfying. A good handheld snack.', '1,500 Ft', '/images/dish-fish-roll.jpg', '{}'::text[], true, false, 7) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('e4d88233-98c0-5ecf-8185-5d8a7ec54929'::uuid, 'drinks', 'Chilled Zobo Drink', 'A chilled hibiscus drink with ginger, cloves, and cinnamon. Tart and refreshing. A Nigerian favorite.', '1,000 Ft', '/images/drink-zobo.jpg', '{}'::text[], true, false, 0) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('5c017d34-bf83-51e7-af2e-c52cc84a96f9'::uuid, 'drinks', 'Chilled Malt 330 ml', 'A chilled non-alcoholic malt drink. Rich and slightly sweet.', '1,000 Ft', '/images/drink-malta.png', '{}'::text[], true, false, 1) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('23a107db-cab3-55cd-8e36-5fbc72a22ef3'::uuid, 'drinks', 'V-soy multi grain drink', 'A chilled multi-grain soy drink. Smooth and lightly sweet.', '1,000 Ft', '/images/drink-vsoy.png', '{}'::text[], true, false, 2) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('dfdb708e-c803-5d05-9b69-19dc56742c1e'::uuid, 'drinks', 'Fanta 330 ml', 'Chilled orange soft drink. 330 ml.', '1,000 Ft', '/images/drink-fanta.png', '{}'::text[], true, false, 3) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();
insert into public.menu_items (id, category_id, name, description, price_label, image_url, tags, is_available, is_featured, sort_order) values ('a59bd04d-3299-53dc-8c69-d7e0d1cfc815'::uuid, 'drinks', 'Coca-Cola Cherry Coke 330 ml', 'Chilled Cherry Coke. 330 ml.', '1,000 Ft', '/images/drink-coke.png', '{}'::text[], true, false, 4) on conflict (id) do update set category_id = excluded.category_id, name = excluded.name, description = excluded.description, price_label = excluded.price_label, image_url = excluded.image_url, tags = excluded.tags, is_available = excluded.is_available, is_featured = excluded.is_featured, sort_order = excluded.sort_order, updated_at = now();

commit;

-- Seed summary: 5 categories, 33 items.
